#cloud-config
coreos:
    units:
      - name: coreos-cloudinit-vagrant.path
        command: start
        runtime: no
        content: |
          [Path]
          PathExists=/var/lib/coreos-vagrant/user-data
          Unit=system-cloudinit@var-lib-coreos\x2dvagrant-user\x2ddata.service
    oem:
      id: vagrant
      name: Vagrant
      home-url: http://www.vagrantup.com/
      bug-report-url: https://github.com/coreos/coreos-overlay

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
