#cloud-config
coreos:
    units:
      - name: coreos-cloudinit-vagrant.path
        command: start
        runtime: no
        content: |
          [Path]
          PathExists=/var/lib/coreos-vagrant/user-data

          [Install]
          WantedBy=multi-user.target
      - name: coreos-cloudinit-vagrant.service
        runtime: no
        content: |
          [Unit]
          ConditionFileNotEmpty=/var/lib/coreos-vagrant/user-data

          [Service]
          Type=oneshot
          EnvironmentFile=-/etc/environment
          ExecStart=/usr/bin/coreos-cloudinit --from-file /var/lib/coreos-vagrant/user-data
          RemainAfterExit=yes
